### ISSUE TITLE
[🐛BUG] SASRecF cannot accept more than one numerical feature

### ISSUE THREAD

**Issue by zhecho1215** [RUCAIBox/RecBole#1554]
Hello I have been trying to add more than one numerical feature to the sequential model SASRecF, but it seems there is a problem in the _recbole/model/layers.py_ file which does not allow for more than one feature to be added. More specifically it is on line 174 in the class FLEmbedding: 
base, index = torch.split(input_x, [1, 1], dim=-1)

The variable input_x seems to have size > 2, when there are more than one feature. So I am wondering if I am doing something wrong or this is expected behaviour?

Here is my yaml file: 
```
field_separator: "\t" 
seq_separator: " " 
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id 
RATING_FIELD: rating 
TIME_FIELD: timestamp 

load_col:
    inter: [user_id, item_id, timestamp]
    item: [item_id,Rank, Days_since_release,Brand,Product_Category]

selected_features: [item_id, Rank, Days_since_release, Brand, Product_Category]
numerical_features: [Rank, Days_since_release]

NEG_PREFIX: neg_ 
ITEM_LIST_LENGTH_FIELD: item_length 
LIST_SUFFIX: _list 
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id 

user_inter_num_interval: [3,200]

epochs: 5 
train_batch_size: 256 
learner: adam 
learning_rate: 0.001 
eval_step: 1 
stopping_step: 10 
training_neg_sample_num: 0

train_neg_sample_args: ~
eval_args:                      # (dict) 4 keys: group_by, order, split, and mode
    split: {'LS': valid_and_test}   # (dict) The splitting strategy ranging in ['RS','LS'].
    group_by: user                # (str) The grouping strategy ranging in ['user', 'none'].
    order: TO                     # (str) The ordering strategy ranging in ['RO', 'TO'].
    mode: full 
eval_setting:
    split:
        LS: valid_and_test
    order: TO
    group_by: user
    mode: full
metrics: ["Recall", "MRR","NDCG","Precision", "Hit"] 
valid_metric: Hit@5
eval_batch_size: 256 
weight_decay: 0
topk: [5, 10, 20]

log_root: "./log/"
data_path: "./dataset/"

lmd: 0.1
lmd_sem: 0.1

tau: 1

contrast: 'us_x'
sim: 'dot'

hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5 
```

**Comment by Sherry-XLL** [comment]
Hello @zhecho1215, I am sorry that there was a problem with the last reply.

> @zhecho1215 Hello, SASRecF is a sequential model, and the feature embedding module is only used for the context-aware models. Therefore, you should not set `numerical_features` in SASRecF, and numerical features are not used in it.

We have fixed the bug you mentioned in #1560, and now SASRecF can accept more than one numerical feature.

The suggestions and feedback from open source users are our driving force for continuous updating. We welcome you very much to use our library again and give your valuable comments.

Closing due to inactivity. Please open a new issue if you're still having questions.

**Comment by kerengaiger** [comment]
@Sherry-XLL Hello, I'm still facing issues passing numerical features to SasRecF, it fails with the following error: RuntimeError: split_with_sizes expects split_sizes to sum exactly to 12 (input tensor's size at dimension -1), but got split_sizes=[1, 1]

**Comment by XinyueYu16** [comment]
@Sherry-XLL Hello, same issue here with DIN and GRU4RecF model. Passing more than one numerical feature into the models would cause the same error. May I ask why we set split_sizes to be [1, 1] here? Would it be more reasonable to change with the actual dimension of float features?

**Comment by thigazholi** [comment]
1. Can user attributes be used with SASRecF like we use item attributes using selected_features? 
2. How do we make sure user attributes contribute to the user embeddings especially in SASRecF. 
3. Do all the models use user features and item features other than user_id and item_id, just when we load the column?

**Comment by willadamskeane** [comment]
I'm running into this issue as well.
